# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dennn/3dscaner

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dennn/3dscaner

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dennn/3dscaner/CMakeFiles /home/dennn/3dscaner/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dennn/3dscaner/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named arduino_driver

# Build rule for target.
arduino_driver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arduino_driver
.PHONY : arduino_driver

# fast build rule for target.
arduino_driver/fast:
	$(MAKE) -f CMakeFiles/arduino_driver.dir/build.make CMakeFiles/arduino_driver.dir/build
.PHONY : arduino_driver/fast

#=============================================================================
# Target rules for targets named calibrate

# Build rule for target.
calibrate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calibrate
.PHONY : calibrate

# fast build rule for target.
calibrate/fast:
	$(MAKE) -f CMakeFiles/calibrate.dir/build.make CMakeFiles/calibrate.dir/build
.PHONY : calibrate/fast

#=============================================================================
# Target rules for targets named capture

# Build rule for target.
capture: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 capture
.PHONY : capture

# fast build rule for target.
capture/fast:
	$(MAKE) -f CMakeFiles/capture.dir/build.make CMakeFiles/capture.dir/build
.PHONY : capture/fast

#=============================================================================
# Target rules for targets named capturelib

# Build rule for target.
capturelib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 capturelib
.PHONY : capturelib

# fast build rule for target.
capturelib/fast:
	$(MAKE) -f CMakeFiles/capturelib.dir/build.make CMakeFiles/capturelib.dir/build
.PHONY : capturelib/fast

#=============================================================================
# Target rules for targets named color_select_helper

# Build rule for target.
color_select_helper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 color_select_helper
.PHONY : color_select_helper

# fast build rule for target.
color_select_helper/fast:
	$(MAKE) -f CMakeFiles/color_select_helper.dir/build.make CMakeFiles/color_select_helper.dir/build
.PHONY : color_select_helper/fast

#=============================================================================
# Target rules for targets named filter

# Build rule for target.
filter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 filter
.PHONY : filter

# fast build rule for target.
filter/fast:
	$(MAKE) -f CMakeFiles/filter.dir/build.make CMakeFiles/filter.dir/build
.PHONY : filter/fast

#=============================================================================
# Target rules for targets named render

# Build rule for target.
render: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 render
.PHONY : render

# fast build rule for target.
render/fast:
	$(MAKE) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/build
.PHONY : render/fast

#=============================================================================
# Target rules for targets named scan

# Build rule for target.
scan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan
.PHONY : scan

# fast build rule for target.
scan/fast:
	$(MAKE) -f CMakeFiles/scan.dir/build.make CMakeFiles/scan.dir/build
.PHONY : scan/fast

#=============================================================================
# Target rules for targets named scanlib

# Build rule for target.
scanlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scanlib
.PHONY : scanlib

# fast build rule for target.
scanlib/fast:
	$(MAKE) -f CMakeFiles/scanlib.dir/build.make CMakeFiles/scanlib.dir/build
.PHONY : scanlib/fast

arduino_driver.o: arduino_driver.cpp.o
.PHONY : arduino_driver.o

# target to build an object file
arduino_driver.cpp.o:
	$(MAKE) -f CMakeFiles/arduino_driver.dir/build.make CMakeFiles/arduino_driver.dir/arduino_driver.cpp.o
.PHONY : arduino_driver.cpp.o

arduino_driver.i: arduino_driver.cpp.i
.PHONY : arduino_driver.i

# target to preprocess a source file
arduino_driver.cpp.i:
	$(MAKE) -f CMakeFiles/arduino_driver.dir/build.make CMakeFiles/arduino_driver.dir/arduino_driver.cpp.i
.PHONY : arduino_driver.cpp.i

arduino_driver.s: arduino_driver.cpp.s
.PHONY : arduino_driver.s

# target to generate assembly for a file
arduino_driver.cpp.s:
	$(MAKE) -f CMakeFiles/arduino_driver.dir/build.make CMakeFiles/arduino_driver.dir/arduino_driver.cpp.s
.PHONY : arduino_driver.cpp.s

calibrate.o: calibrate.cpp.o
.PHONY : calibrate.o

# target to build an object file
calibrate.cpp.o:
	$(MAKE) -f CMakeFiles/calibrate.dir/build.make CMakeFiles/calibrate.dir/calibrate.cpp.o
.PHONY : calibrate.cpp.o

calibrate.i: calibrate.cpp.i
.PHONY : calibrate.i

# target to preprocess a source file
calibrate.cpp.i:
	$(MAKE) -f CMakeFiles/calibrate.dir/build.make CMakeFiles/calibrate.dir/calibrate.cpp.i
.PHONY : calibrate.cpp.i

calibrate.s: calibrate.cpp.s
.PHONY : calibrate.s

# target to generate assembly for a file
calibrate.cpp.s:
	$(MAKE) -f CMakeFiles/calibrate.dir/build.make CMakeFiles/calibrate.dir/calibrate.cpp.s
.PHONY : calibrate.cpp.s

capture.o: capture.cpp.o
.PHONY : capture.o

# target to build an object file
capture.cpp.o:
	$(MAKE) -f CMakeFiles/capture.dir/build.make CMakeFiles/capture.dir/capture.cpp.o
.PHONY : capture.cpp.o

capture.i: capture.cpp.i
.PHONY : capture.i

# target to preprocess a source file
capture.cpp.i:
	$(MAKE) -f CMakeFiles/capture.dir/build.make CMakeFiles/capture.dir/capture.cpp.i
.PHONY : capture.cpp.i

capture.s: capture.cpp.s
.PHONY : capture.s

# target to generate assembly for a file
capture.cpp.s:
	$(MAKE) -f CMakeFiles/capture.dir/build.make CMakeFiles/capture.dir/capture.cpp.s
.PHONY : capture.cpp.s

capturelib.o: capturelib.cpp.o
.PHONY : capturelib.o

# target to build an object file
capturelib.cpp.o:
	$(MAKE) -f CMakeFiles/capturelib.dir/build.make CMakeFiles/capturelib.dir/capturelib.cpp.o
.PHONY : capturelib.cpp.o

capturelib.i: capturelib.cpp.i
.PHONY : capturelib.i

# target to preprocess a source file
capturelib.cpp.i:
	$(MAKE) -f CMakeFiles/capturelib.dir/build.make CMakeFiles/capturelib.dir/capturelib.cpp.i
.PHONY : capturelib.cpp.i

capturelib.s: capturelib.cpp.s
.PHONY : capturelib.s

# target to generate assembly for a file
capturelib.cpp.s:
	$(MAKE) -f CMakeFiles/capturelib.dir/build.make CMakeFiles/capturelib.dir/capturelib.cpp.s
.PHONY : capturelib.cpp.s

color_select_helper.o: color_select_helper.cpp.o
.PHONY : color_select_helper.o

# target to build an object file
color_select_helper.cpp.o:
	$(MAKE) -f CMakeFiles/color_select_helper.dir/build.make CMakeFiles/color_select_helper.dir/color_select_helper.cpp.o
.PHONY : color_select_helper.cpp.o

color_select_helper.i: color_select_helper.cpp.i
.PHONY : color_select_helper.i

# target to preprocess a source file
color_select_helper.cpp.i:
	$(MAKE) -f CMakeFiles/color_select_helper.dir/build.make CMakeFiles/color_select_helper.dir/color_select_helper.cpp.i
.PHONY : color_select_helper.cpp.i

color_select_helper.s: color_select_helper.cpp.s
.PHONY : color_select_helper.s

# target to generate assembly for a file
color_select_helper.cpp.s:
	$(MAKE) -f CMakeFiles/color_select_helper.dir/build.make CMakeFiles/color_select_helper.dir/color_select_helper.cpp.s
.PHONY : color_select_helper.cpp.s

filter.o: filter.cpp.o
.PHONY : filter.o

# target to build an object file
filter.cpp.o:
	$(MAKE) -f CMakeFiles/filter.dir/build.make CMakeFiles/filter.dir/filter.cpp.o
.PHONY : filter.cpp.o

filter.i: filter.cpp.i
.PHONY : filter.i

# target to preprocess a source file
filter.cpp.i:
	$(MAKE) -f CMakeFiles/filter.dir/build.make CMakeFiles/filter.dir/filter.cpp.i
.PHONY : filter.cpp.i

filter.s: filter.cpp.s
.PHONY : filter.s

# target to generate assembly for a file
filter.cpp.s:
	$(MAKE) -f CMakeFiles/filter.dir/build.make CMakeFiles/filter.dir/filter.cpp.s
.PHONY : filter.cpp.s

render.o: render.cpp.o
.PHONY : render.o

# target to build an object file
render.cpp.o:
	$(MAKE) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/render.cpp.o
.PHONY : render.cpp.o

render.i: render.cpp.i
.PHONY : render.i

# target to preprocess a source file
render.cpp.i:
	$(MAKE) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/render.cpp.i
.PHONY : render.cpp.i

render.s: render.cpp.s
.PHONY : render.s

# target to generate assembly for a file
render.cpp.s:
	$(MAKE) -f CMakeFiles/render.dir/build.make CMakeFiles/render.dir/render.cpp.s
.PHONY : render.cpp.s

scan.o: scan.cpp.o
.PHONY : scan.o

# target to build an object file
scan.cpp.o:
	$(MAKE) -f CMakeFiles/scan.dir/build.make CMakeFiles/scan.dir/scan.cpp.o
.PHONY : scan.cpp.o

scan.i: scan.cpp.i
.PHONY : scan.i

# target to preprocess a source file
scan.cpp.i:
	$(MAKE) -f CMakeFiles/scan.dir/build.make CMakeFiles/scan.dir/scan.cpp.i
.PHONY : scan.cpp.i

scan.s: scan.cpp.s
.PHONY : scan.s

# target to generate assembly for a file
scan.cpp.s:
	$(MAKE) -f CMakeFiles/scan.dir/build.make CMakeFiles/scan.dir/scan.cpp.s
.PHONY : scan.cpp.s

scanlib.o: scanlib.cpp.o
.PHONY : scanlib.o

# target to build an object file
scanlib.cpp.o:
	$(MAKE) -f CMakeFiles/scanlib.dir/build.make CMakeFiles/scanlib.dir/scanlib.cpp.o
.PHONY : scanlib.cpp.o

scanlib.i: scanlib.cpp.i
.PHONY : scanlib.i

# target to preprocess a source file
scanlib.cpp.i:
	$(MAKE) -f CMakeFiles/scanlib.dir/build.make CMakeFiles/scanlib.dir/scanlib.cpp.i
.PHONY : scanlib.cpp.i

scanlib.s: scanlib.cpp.s
.PHONY : scanlib.s

# target to generate assembly for a file
scanlib.cpp.s:
	$(MAKE) -f CMakeFiles/scanlib.dir/build.make CMakeFiles/scanlib.dir/scanlib.cpp.s
.PHONY : scanlib.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... arduino_driver"
	@echo "... calibrate"
	@echo "... capture"
	@echo "... capturelib"
	@echo "... color_select_helper"
	@echo "... edit_cache"
	@echo "... filter"
	@echo "... rebuild_cache"
	@echo "... render"
	@echo "... scan"
	@echo "... scanlib"
	@echo "... arduino_driver.o"
	@echo "... arduino_driver.i"
	@echo "... arduino_driver.s"
	@echo "... calibrate.o"
	@echo "... calibrate.i"
	@echo "... calibrate.s"
	@echo "... capture.o"
	@echo "... capture.i"
	@echo "... capture.s"
	@echo "... capturelib.o"
	@echo "... capturelib.i"
	@echo "... capturelib.s"
	@echo "... color_select_helper.o"
	@echo "... color_select_helper.i"
	@echo "... color_select_helper.s"
	@echo "... filter.o"
	@echo "... filter.i"
	@echo "... filter.s"
	@echo "... render.o"
	@echo "... render.i"
	@echo "... render.s"
	@echo "... scan.o"
	@echo "... scan.i"
	@echo "... scan.s"
	@echo "... scanlib.o"
	@echo "... scanlib.i"
	@echo "... scanlib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

